In [2]:
import os
import cv2
import numpy as np

In [3]:
original_dataset_dir = 'C:\data\celebaMask\CelebAMask-HQ'
img_folder_list = os.listdir(original_dataset_dir+'/CelebA-HQ-img')
folder_list = os.listdir(original_dataset_dir)
anno_folder_list = os.listdir(os.path.join(original_dataset_dir,'CelebAMask-HQ-mask-anno'))

""" 이름이 0~14폴더 정렬시키기"""
num_arr = anno_folder_list.copy()
for idx, e in enumerate(anno_folder_list):
    num_arr[idx] = int(e)
num_arr.sort()
for idx, e in enumerate(num_arr):
    num_arr[idx] = str(e)
num_arr

""" 각 숫자폴더에 있는 파일리스트 받아오기 """
anno_folder_list = os.path.join(original_dataset_dir,'CelebAMask-HQ-mask-anno')
anno_file_list = []
for e in num_arr:
    anno_file_list.append(os.listdir(os.path.join(anno_folder_list, e)))

anno_file_list[:400]

""" 0~14 폴더에서 마스크 이름 가져오기 """
find_list = ['skin.png','neck.png','hair.png','ear.png'] # 특정 마스크
anno_list = [] # 숫자 폴더 주소 리스트
for e in num_arr:
    anno_list.append(os.path.join(anno_folder_list, e))
found_list = []
for e in anno_list:
    ls = os.listdir(e) # 숫자 폴더의 이미지 리스트
    fl = []
    for i in ls:
        if i.split('_')[-1] in find_list:
            fl.append(i)
    found_list.append(fl)
found_list

[['00000_hair.png',
  '00000_neck.png',
  '00000_skin.png',
  '00001_hair.png',
  '00001_l_ear.png',
  '00001_neck.png',
  '00001_r_ear.png',
  '00001_skin.png',
  '00002_hair.png',
  '00002_l_ear.png',
  '00002_neck.png',
  '00002_skin.png',
  '00003_hair.png',
  '00003_neck.png',
  '00003_skin.png',
  '00004_hair.png',
  '00004_l_ear.png',
  '00004_neck.png',
  '00004_skin.png',
  '00005_hair.png',
  '00005_neck.png',
  '00005_skin.png',
  '00006_hair.png',
  '00006_neck.png',
  '00006_skin.png',
  '00007_hair.png',
  '00007_l_ear.png',
  '00007_neck.png',
  '00007_r_ear.png',
  '00007_skin.png',
  '00008_hair.png',
  '00008_l_ear.png',
  '00008_neck.png',
  '00008_skin.png',
  '00009_hair.png',
  '00009_neck.png',
  '00009_r_ear.png',
  '00009_skin.png',
  '00010_hair.png',
  '00010_neck.png',
  '00010_r_ear.png',
  '00010_skin.png',
  '00011_hair.png',
  '00011_neck.png',
  '00011_r_ear.png',
  '00011_skin.png',
  '00012_hair.png',
  '00012_neck.png',
  '00012_skin.png',
  '00013_h

In [4]:
""" 복사 절대주소 만들기 """
copy_files = []
for idx, al in enumerate(anno_list):
    for fl in found_list[idx]:
        copy_files.append(os.path.join(al, fl))
        
copy_files

['C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00000_hair.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00000_neck.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00000_skin.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00001_hair.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00001_l_ear.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00001_neck.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00001_r_ear.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00001_skin.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00002_hair.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00002_l_ear.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00002_neck.png',
 'C:\\data\\celebaMask\\CelebAMask-HQ\\CelebAMask-HQ-mask-anno\\0\\00002_

In [5]:
# """ 복사하기 """
# import shutil
# copy_files
# dest = 'C:\data\celebaMask\dataset\mask'

# for i in copy_files:
#     shutil.copy2(i,dest)

In [15]:
import cv2 
from glob import glob
import numpy as np
""" 얼굴 귀 합치기"""
dataset_dir = 'C:\\data\\celebaMask\\dataset'
png_list = glob(dataset_dir+'\\*.png') # glob 장점, *.png png파일만 가져올 수 있음, os.listdir 오류남

img1 = cv2.imread(png_list[0], cv2.IMREAD_GRAYSCALE)
img1 = cv2.resize(img1, (512, 512))
img1 = cv2.cvtColor(img1,cv2.COLOR_BGR2BGRA)

img2 = cv2.imread(png_list[1], cv2.IMREAD_GRAYSCALE)
img2 = cv2.resize(img2, (512, 512))
img2 = cv2.cvtColor(img2,cv2.COLOR_BGR2BGRA)

img3 = cv2.imread(png_list[2], cv2.IMREAD_GRAYSCALE)
img3 = cv2.resize(img3, (512, 512))
img3 = cv2.cvtColor(img3,cv2.COLOR_BGR2BGRA)

print(np.shape(img1), np.shape(img2), np.shape(img3))

for i in range(len(img1)):
    for j in range(len(img1[0])):
        if (img1[j][i] == [0,0,0,255]).all():
            img1[j][i] = [0,0,0,0]
            
for i in range(len(img2)):
    for j in range(len(img2[0])):
        if (img2[j][i] == [0,0,0,255]).all():
            img2[j][i] = [0,0,0,0]
            
for i in range(len(img3)):
    for j in range(len(img3[0])):
        if (img3[j][i] == [0,0,0,255]).all():
            img3[j][i] = [0,0,0,0]
            
mimg = img1 + img2 + img3
mimg = cv2.cvtColor(mimg, cv2.COLOR_BGRA2BGR)
print(np.shape(mimg))
print(mimg)
# cv2.imshow('img',mimg)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
cv2.imwrite('C:\data\celebaMask\dataset\img.png',mimg)


(512, 512, 4) (512, 512, 4) (512, 512, 4)
(512, 512, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


True

In [3]:
import cv2 
from glob import glob
import numpy as np

""" 얼굴과 귀가 있는 파일 불러와서 하나의 딕셔너리로 정리하기 """
dataset_dir = 'C:\\data\\celebaMask\\dataset\\mask'

ears_list = glob(dataset_dir+'\\*ear.png') # glob 장점, *.png png파일만 가져올 수 있음, os.listdir 오류남
skin_list = glob(dataset_dir+'\\*skin.png')
ears_list, skin_list

skin_dict = {}
for i in skin_list:
    skin_id = i.split('\\')[-1].split('_')[0]
    skin_address = i
    skin_dict[skin_id] = skin_address
    
file_dict = {}
for i in ears_list:
    ears_id = i.split('\\')[-1].split('_')[0]
    ears_address = i
    if ears_id not in file_dict:
        file_dict[ears_id] = []
    file_dict[ears_id].append(ears_address)
        
for i in skin_dict.items():
    if i[0] in file_dict.keys():
        file_dict[i[0]].append(i[1])
file_dict

{'00001': ['C:\\data\\celebaMask\\dataset\\mask\\00001_l_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00001_r_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00001_skin.png'],
 '00002': ['C:\\data\\celebaMask\\dataset\\mask\\00002_l_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00002_skin.png'],
 '00004': ['C:\\data\\celebaMask\\dataset\\mask\\00004_l_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00004_skin.png'],
 '00007': ['C:\\data\\celebaMask\\dataset\\mask\\00007_l_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00007_r_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00007_skin.png'],
 '00008': ['C:\\data\\celebaMask\\dataset\\mask\\00008_l_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00008_skin.png'],
 '00009': ['C:\\data\\celebaMask\\dataset\\mask\\00009_r_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00009_skin.png'],
 '00010': ['C:\\data\\celebaMask\\dataset\\mask\\00010_r_ear.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00010_skin.png'],
 '00011':

In [3]:
len(file_dict)

20801

In [9]:
img_dict = {}

for filename in list(file_dict.keys())[:5000]: 
    for img in file_dict[filename]:
        img = cv2.imread(img, cv2.IMREAD_UNCHANGED)
        img = cv2.resize(img, (512, 512))
        if filename not in img_dict:
            img_dict[filename] = []
        img_dict[filename].append(img)

KeyboardInterrupt: 

In [33]:
len(file_dict)

20801

In [6]:
# for filename in list(file_dict.keys())[:5000]:
    
#     imgs = img_dict[filename]
    
#     for k in imgs:
#         for i in range(len(k)):
#             for j in range(len(k[0])):
#                 if (k[j][i] == [255,255,255]).all():
#                     k[j][i] = [1,1,1]
    
#     mimg = imgs[0]
#     for img in imgs:
#         mimg = cv2.bitwise_or(mimg,img) # 1 or 1 = 1, 1 or 2 = 3
    
#     cv2.imwrite(f'C:\data\celebaMask\dataset\skin\{filename}_skin.png',mimg)
#     len(os.listdir('C:\data\celebaMask\dataset\skin'))

In [7]:

""" 귀와 얼굴을 합친 스킨에 맞는 헤어와 목 가져오기 """
import cv2 
from glob import glob
import numpy as np

""" 얼굴과 귀가 있는 파일 불러와서 하나의 딕셔너리로 정리하기 """
dataset_dir = 'C:\\data\\celebaMask\\dataset'

hair_list = glob(dataset_dir+'\\mask\\*hair.png') # glob 장점, *.png png파일만 가져올 수 있음, os.listdir 오류남
neck_list = glob(dataset_dir+'\\mask\\*neck.png')
skin_list = glob(dataset_dir+'\\skin\\*skin.png')

select_dict = {}

for i in file_dict.keys():
    select_dict[i] = []

for i in hair_list:
    hair_name = i.split('\\')[-1].split('_')[0]
    if hair_name in file_dict.keys():
        select_dict[hair_name] = []
        select_dict[hair_name].append(i)

for i in neck_list:
    neck_name = i.split('\\')[-1].split('_')[0]
    if neck_name in file_dict.keys():
        select_dict[neck_name].append(i)

for i in skin_list:
    skin_name = i.split('\\')[-1].split('_')[0]
    if skin_name in file_dict.keys():
        select_dict[skin_name].append(i)
select_dict

{'00001': ['C:\\data\\celebaMask\\dataset\\mask\\00001_hair.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00001_neck.png',
  'C:\\data\\celebaMask\\dataset\\skin\\00001_skin.png'],
 '00002': ['C:\\data\\celebaMask\\dataset\\mask\\00002_hair.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00002_neck.png',
  'C:\\data\\celebaMask\\dataset\\skin\\00002_skin.png'],
 '00004': ['C:\\data\\celebaMask\\dataset\\mask\\00004_hair.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00004_neck.png',
  'C:\\data\\celebaMask\\dataset\\skin\\00004_skin.png'],
 '00007': ['C:\\data\\celebaMask\\dataset\\mask\\00007_hair.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00007_neck.png',
  'C:\\data\\celebaMask\\dataset\\skin\\00007_skin.png'],
 '00008': ['C:\\data\\celebaMask\\dataset\\mask\\00008_hair.png',
  'C:\\data\\celebaMask\\dataset\\mask\\00008_neck.png',
  'C:\\data\\celebaMask\\dataset\\skin\\00008_skin.png'],
 '00009': ['C:\\data\\celebaMask\\dataset\\mask\\00009_hair.png',
  'C:\\data\\celebaMask\\data

In [12]:
for i in list(select_dict.keys())[:5000]:
    print(select_dict[i])

# skin_dict = {}
# for i in skin_list:
#     skin_id = i.split('\\')[-1].split('_')[0]
#     skin_address = i
#     skin_dict[skin_id] = skin_address
    
# file_dict = {}
# for i in ears_list:
#     ears_id = i.split('\\')[-1].split('_')[0]
#     ears_address = i
#     if ears_id not in file_dict:
#         file_dict[ears_id] = []
#     file_dict[ears_id].append(ears_address)
        
# for i in skin_dict.items():
#     if i[0] in file_dict.keys():
#         file_dict[i[0]].append(i[1])
# file_dict

['C:\\data\\celebaMask\\dataset\\mask\\00001_hair.png', 'C:\\data\\celebaMask\\dataset\\mask\\00001_neck.png', 'C:\\data\\celebaMask\\dataset\\skin\\00001_skin.png']
['C:\\data\\celebaMask\\dataset\\mask\\00002_hair.png', 'C:\\data\\celebaMask\\dataset\\mask\\00002_neck.png', 'C:\\data\\celebaMask\\dataset\\skin\\00002_skin.png']
['C:\\data\\celebaMask\\dataset\\mask\\00004_hair.png', 'C:\\data\\celebaMask\\dataset\\mask\\00004_neck.png', 'C:\\data\\celebaMask\\dataset\\skin\\00004_skin.png']
['C:\\data\\celebaMask\\dataset\\mask\\00007_hair.png', 'C:\\data\\celebaMask\\dataset\\mask\\00007_neck.png', 'C:\\data\\celebaMask\\dataset\\skin\\00007_skin.png']
['C:\\data\\celebaMask\\dataset\\mask\\00008_hair.png', 'C:\\data\\celebaMask\\dataset\\mask\\00008_neck.png', 'C:\\data\\celebaMask\\dataset\\skin\\00008_skin.png']
['C:\\data\\celebaMask\\dataset\\mask\\00009_hair.png', 'C:\\data\\celebaMask\\dataset\\mask\\00009_neck.png', 'C:\\data\\celebaMask\\dataset\\skin\\00009_skin.png']
['C:

In [18]:
hair = "C:\data\celebaMask\dataset\\00002_hair.png"
skins = "C:\\data\\celebaMask\\dataset\\skin\\00002_skin.png"
neck = "C:\\data\\celebaMask\\dataset\\00002_neck.png"

img1 = cv2.imread(hair, cv2.IMREAD_UNCHANGED)
img1 = cv2.resize(img1, (512, 512))

img2 = cv2.imread(skins, cv2.IMREAD_UNCHANGED)
img2 = cv2.resize(img2, (512, 512))

img3 = cv2.imread(neck, cv2.IMREAD_UNCHANGED)
img3 = cv2.resize(img3, (512, 512))

# 헤어 컬러 변경
for i in range(len(img1)):
    for j in range(len(img1[0])):
        if (img1[j][i] == [255,255,255]).all():
            img1[j][i] = [2,2,2]
            
mimg = cv2.bitwise_or(img1,img2)

# 목과 헤어 겹치는 부위 수정 
for i in range(len(mimg)):
    for j in range(len(mimg[0])):
        if (mimg[j][i] == [3,3,3]).all():
            mimg[j][i] = [2,2,2]

# 목 컬러 변경
for i in range(len(img3)):
    for j in range(len(img3[0])):
        if (img3[j][i] == [255,255,255]).all():
            img3[j][i] = [3,3,3]

# 합치기
mimg = cv2.bitwise_or(mimg,img3)

# cv2.imshow("img",mimg)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

cv2.imwrite(f'C:\data\celebaMask\dataset\{filename}_m.png',mimg)

(512, 512, 3) (512, 512, 3)


True