In [1]:
################################################33
#### 얼굴인식 하는 xml자료 연동하기
#### 이미지 자료 읽기
###########################################
import cv2

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml') #정면인식하는 코드

In [2]:
BASE_URL = 'C:/data/cascade_cv2/'

In [3]:
img = cv2.imread(BASE_URL+'open_cv_1.jpg')  # cv2는 기본으로 array로 들어옴
#gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)   # gray모델은 필요에 따라 사용함. 여기서는 사용하지 않겠음.

faces = face_cascade.detectMultiScale(img, 1.1, 5)
faces   # 출력되는 값은 얼굴인식한 위치값에 대한 정보임

array([[452, 102,  58,  58],
       [366, 122,  54,  54],
       [272, 180,  52,  52],
       [573, 122,  60,  60],
       [130, 159,  55,  55]])

In [4]:
cnt = 0
for x,y,w,h in faces:
    cv2.rectangle(img, (x-20, y-20), (x + w+20, y + h+20), (255, 0, 0), 2)  
    cnt+=1
    cv2.putText(img, str(cnt) , (x,y-30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 2)
    
cv2.imshow("test", img)   #  cv2.imshow('캡션명 사용자 마음임',출력할 이미지 변수명)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
# 여자0, 남자 1로 성별 구별하는 모델 (티처블머신러닝에서 작업함)

from keras.models import load_model
model = load_model(BASE_URL+'model4.h5')  

#model.weights


In [11]:
import cv2
import numpy as np
from glob import glob

class_name=['Female','Male']     
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# 이미지 사이즈
IMG_SIZE = 160

# 이미지 불러오기
img = cv2.imread(BASE_URL+'open_cv_1.jpg')

# 얼굴 찾기
faces = face_cascade.detectMultiScale(img, 1.1, 5)

cnt=0
for (x, y, w, h) in faces:
    rect_arr = img[y-20:y + h+20, x-20:x + w+20]
    
    ### 모델에 넣기 위한 작업
    resize_img = cv2.resize(rect_arr, (IMG_SIZE, IMG_SIZE))
    imgArr=(resize_img/127.0)-1   # 티처블 코드에 있었음
    prediction=imgArr.reshape(1,IMG_SIZE,IMG_SIZE,3) # 인공지능은  array 를 하나 확장한 tensor로 해야함. (224,224,3)을 1,224,224,3 으로 확장함
    prediction = model.predict(prediction)
    argmaxNumber=np.argmax(prediction)   # 출력결과가 0이면 0번째 위치값이 predict 출력값중에 0번째 위치값이 가장 크다는 뜻
    printTxt=class_name[argmaxNumber]
    cv2.putText(img, printTxt , (x-10,y-30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 2)
    
    roi = rect_arr
    Number = len(glob('./saveImg/*'))
    newName = printTxt + "-"+ str(Number)
    cv2.imwrite('./saveImg/'+  newName +'.png', roi)
    
    cv2.rectangle(img, (x-20, y-20), (x + w+20, y + h+20), (255, 0, 0), 2)
    print(newName)
    
cv2.imshow("test", img) #   cv2.imshow('캡션명 사용자 마음임',출력할 이미지 변수명)
cv2.waitKey()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 20ms/step
Female-2
1/1 [==============================] - 0s 20ms/step
Female-3
1/1 [==============================] - 0s 19ms/step
Male-4
1/1 [==============================] - 0s 20ms/step
Male-5
1/1 [==============================] - 0s 20ms/step
Female-6


In [21]:
import cv2
import numpy as np
from glob import glob
import tensorflow as tf

class_name=['Female','Male']     
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# 이미지 사이즈
IMG_SIZE = 160

# 이미지 불러오기
img = cv2.imread(BASE_URL+'open_cv_2.jpg')

# 얼굴 찾기
faces = face_cascade.detectMultiScale(img, 1.1, 5)

cnt=0
for (x, y, w, h) in faces:
    rect_arr = img[y-20:y + h+20, x-20:x + w+20]
    
    ### 모델에 넣기 위한 작업
    resize_img = cv2.resize(rect_arr, (IMG_SIZE, IMG_SIZE))
    imgArr=(resize_img) # 티처블 코드에 있었음
    prediction=imgArr.reshape(1,IMG_SIZE,IMG_SIZE,3) # 인공지능은  array 를 하나 확장한 tensor로 해야함. (224,224,3)을 1,224,224,3 으로 확장함
    prediction = model.predict(prediction)
    
    prediction = tf.nn.sigmoid(prediction)
    argmaxNumber=np.argmax(prediction)   # 출력결과가 0이면 0번째 위치값이 predict 출력값중에 0번째 위치값이 가장 크다는 뜻
    printTxt=class_name[argmaxNumber]
    cv2.putText(img, printTxt , (x-10,y-30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0), 2)
    print(prediction)
    print(argmaxNumber)
    # roi = rect_arr
    # Number = len(glob('./saveImg/*'))
    # newName = printTxt + "-"+ str(Number)
    # cv2.imwrite('./saveImg/'+  newName +'.png', roi)
    
    cv2.rectangle(img, (x-20, y-20), (x + w+20, y + h+20), (255, 0, 0), 2)
    print(newName)
    
cv2.imshow("test", img) #   cv2.imshow('캡션명 사용자 마음임',출력할 이미지 변수명)
cv2.waitKey()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 22ms/step
tf.Tensor([[0.01050253]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 27ms/step
tf.Tensor([[0.29395527]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 24ms/step
tf.Tensor([[0.05605894]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 24ms/step
tf.Tensor([[0.00698124]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 21ms/step
tf.Tensor([[0.43198135]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 24ms/step
tf.Tensor([[0.7590141]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 24ms/step
tf.Tensor([[0.00884872]], shape=(1, 1), dtype=float32)
0
Female-4
1/1 [==============================] - 0s 21ms/step
tf.Tensor([[0.02068004]], shape=(1, 1), dtype=float32)
0
Female-4


In [12]:
import os
import shutil


SAVE_URL = './saveImg/'
newDir = SAVE_URL+class_name[argmaxNumber]
if not os.path.exists(SAVE_URL+class_name[argmaxNumber]):
    os.mkdir(newDir)
shutil.move(SAVE_URL+newName+'.png', newDir)

Error: Destination path './saveImg/Female\Female-6.png' already exists