In [1]:
import torch

In [2]:
import tensorflow as tf

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.


In [13]:
### 텐서플로우도 자체 변수가 있다
# 인덱싱해서 값을 변경 할 수 없다 # 텐서로 감싸져 있어서
# assign() 호출해야 값 변경 가능

vartf = tf.Variable([1,2,3])
# vartf[0] = 5 
type(vartf)
vartf[0].assign(100)
b = tf.constant([1,2,3])
# b[0].assign(100) # tf.Variable이 아니라서 안된다
aa = [1,2,3]
bb = tf.constant(aa)
bb, tf.convert_to_tensor(aa)


(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [6]:
### 파이토치는 텐서가 있어도 바로 데이터를 변경할 수 있다

varto = torch.tensor([1,2,3])
type(varto)
varto[0] = 100
varto

tensor([100,   2,   3])